# Roles

###
# @name Create Role
GET

###
# @name Get Applications
GET {{host}}/api/v1/application
Authorization: Bearer {{token}}
#
####
## @name Get Role
#GET {{host}}/api/v1/role/admin-readwrite
#Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImFueXRoaW5nIiwicm9sZXMiOlsiYWRtaW4iXX0.GIdLW6fmKuxENzwAdLNbQcnaZSNnkTmeh_qDsjSx4zA
#
#> {%
#    const token = client.global.get("token");
#    if (!token) {
#        client.log("No token found. Run the Login request first.");
#    }
#    const expiry = Number(client.global.get("token_expiry") || 0);
#    if (expiry && Date.now() > expiry) {
#        client.log("Token appears expired. Run the Login request again.");
#    }
#%}
#
