# Roles

###
### 
# @name Create Application
POST {{host}}/api/v1/application
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "new-application",
  "description": "Description",
  "imageUrl": "",
  "targetUrl": "",
  "isDefaultApplicationOnLogin": false,
  "ordinal": 1,
  "addToRoles": [
    "new-role"
  ]
}

###
# @name Get Applications
GET {{host}}/api/v1/application
Authorization: Bearer {{token}}
#

###
# @name Get Applications by text
GET {{host}}/api/v1/application?containsText=Description
Authorization: Bearer {{token}}

###
# @name Get Applications by text
GET {{host}}/api/v1/application?withinRoles=new-role2
Authorization: Bearer {{token}}

###
# @name Get Application
GET {{host}}/api/v1/application/new-application
Authorization: Bearer {{token}}
#

###
# @name Get Application Health
GET {{host}}/api/v1/application/administration/health
Authorization: Bearer {{token}}
#

###
# @name Get all Application Health
GET {{host}}/api/v1/application/health
Authorization: Bearer {{token}}
#


###
# @name Update Application
PUT {{host}}/api/v1/application/new-application
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "targetUrl": "",
  "name": "new-application2",
  "description": "description2"
}


###
# @name Delete Application
DELETE {{host}}/api/v1/application/new-application2
Authorization: Bearer {{token}}

