# Users

###
# @name Create User
POST {{host}}/api/v1/user
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "userName": "nathan-test {{$isoTimestamp}}",
  "emailAddress": "nathan@programx.co.uk",
  "addToRoles": [
    "impersonatable",
    "admin-readonly"
  ],
  "firstName": "Nathan 2 {{$isoTimestamp}}",
  "lastName": "Pledger",
  "passwordConfirmationLinkExpiryDate": "2025-12-31T23:59:59"
}

###
# @name Update User
PUT {{host}}/api/v1/user/nathan-test
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "userName": "nathan-test",
  "emailAddress": "testEmail",
  "password": "password",
  "addToRoles": []
}

###
# @name Get User
GET {{host}}/api/v1/user/e5d3203dab3648be91b529de493efd27
Authorization: Bearer {{token}}

###
# @name Get Users
GET {{host}}/api/v1/user
Authorization: Bearer {{token}}

###
# @name Get Users containing text
GET {{host}}/api/v1/user?containsText=xx
Authorization: Bearer {{token}}

###
# @name Get Users with role
GET {{host}}/api/v1/user?withRoles=admin-readonly
Authorization: Bearer {{token}}

###
# @name Get Users with access to application
GET {{host}}/api/v1/user?hasAccessToApplications=Home
Authorization: Bearer {{token}}

###
# @name Get Page 3
GET {{host}}/api/v1/user?offset=10&itemsPerPage=5
Authorization: Bearer {{token}}

###
# @name Delete user
DELETE {{host}}/api/v1/user/NathanTest9
Authorization: Bearer {{token}}