# Users

###
# @name Create User
POST {{host}}/api/v1/user
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "userName": "nathan-test {{$isoTimestamp}}",
  "emailAddress": "nathan@programx.co.uk",
  "addToRoles": [
    "impersonatable",
    "admin-readonly"
  ],
  "firstName": "Nathan 2 {{$isoTimestamp}}",
  "lastName": "Pledger",
  "passwordConfirmationLinkExpiryDate": "2025-12-31T23:59:59"
}

###
# @name Update User
PUT {{host}}/api/v1/user/nathan-test
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "userName": "nathan-test",
  "emailAddress": "testEmail",
  "password": "password",
  "addToRoles": []
}

###
# @name Get User
GET {{host}}/api/v1/user/e5d3203dab3648be91b529de493efd27
Authorization: Bearer {{token}}

###
# @name Get Users
GET {{host}}/api/v1/user
Authorization: Bearer {{token}}

###
# @name Get Users containing text
GET {{host}}/api/v1/user?containsText=xx
Authorization: Bearer {{token}}

###
# @name Get Users with role
GET {{host}}/api/v1/user?withRoles=admin-readonly
Authorization: Bearer {{token}}

###
# @name Get Users with access to application
GET {{host}}/api/v1/user?hasAccessToApplications=Home
Authorization: Bearer {{token}}

###
# @name Get Page 3
GET {{host}}/api/v1/user?offset=10&itemsPerPage=5
Authorization: Bearer {{token}}

###
GET http://localhost:7276/api/v1/user?containsText=t&continuationToken=%7B%22OptimisticDirectExecutionToken%22%3A%7B%22token%22%3A%22%2BRID%3A~fahmANNVhRonAAAAAAAAAA%3D%3D%23RT%3A1%23TRC%3A5%23RTD%3AT8SNn3c92%2FvoSTjZ4ohMBU9idWlib1VmdHU3AA%3D%3D%23ISV%3A2%23IEO%3A65567%23QCF%3A8%23FPC%3AASIAAAAAAAAALQAAAAAAAAA%3D%22%2C%22range%22%3A%7B%22min%22%3A%22%22%2C%22max%22%3A%22FF%22%7D%7D%7D
Authorization: Bearer {{token}}