using System.Text.Json.Serialization;

namespace ProgramX.Azure.FunctionApp.Model.Requests;

/// <summary>
/// Represents a request to update a user.
/// </summary>
public class UpdateUserPasswordRequest
{
    /// <summary>
    /// The user's current password.
    /// </summary>
    [JsonPropertyName("currentPassword")]
    public string CurrentPassword { get; set; }

    /// <summary>
    /// The new password of the user. To set a new password, the user must have the "updatePasswordScope" property set.
    /// </summary>
    [JsonPropertyName("newPassword")]
    public string NewPassword { get; set; }
    

    /// <summary>
    /// The nonce used to confirm the password change. The nonce is generated by the client (usually email application) and must be sent back to the server along with the new password.
    /// </summary>
    [JsonPropertyName("passwordConfirmationNonce")]
    public string PasswordConfirmationNonce { get; set; }
    
}