using System.Text.Json.Serialization;

namespace ProgramX.Azure.FunctionApp.Model.Requests;

/// <summary>
/// Represents a request to update a user.
/// </summary>
public class UpdateUserPasswordRequest
{
    /// <summary>
    /// The new email address of the user. To update this, the user must have the "updateProfileScope" property set.
    /// </summary>
    [JsonPropertyName("emailAddress")]
    public string? EmailAddress { get; set; }
    
    /// <summary>
    /// The new username of the user.
    /// </summary>
    /// <remarks>
    /// It is not possible to change the username of a user.
    /// </remarks>
    [JsonPropertyName("userName")]
    public required string UserName { get; set; }

    /// <summary>
    /// The new first and last name of the user. To update these, the user must have the "updateProfileScope" property set.
    /// </summary>
    [JsonPropertyName("firstName")]
    public string? FirstName { get; set; }

    /// <summary>
    /// The new last name of the user. To update this, the user must have the "updateProfileScope" property set.
    /// </summary>
    [JsonPropertyName("lastName")]
    public string? LastName { get; set; }

    /// <summary>
    /// Set to true to update the user's profile.
    /// </summary>
    [JsonPropertyName("updateProfileScope")]
    public  bool UpdateProfileScope { get; set; } = false;

    /// <summary>
    /// Set to true to update the user's password.
    /// </summary>
    [JsonPropertyName("updatePasswordScope")]
    public bool UpdatePasswordScope { get; set; } = false;

    /// <summary>
    /// Set to true to update the user's profile picture.
    /// </summary>
    [JsonPropertyName("updateProfilePictureScope")]
    public bool UpdateProfilePictureScope { get; set; } = false;
    
    /// <summary>
    /// Set to true to update the user's roles.
    /// </summary>
    [JsonPropertyName("updateRolesScope")]
    public bool UpdateRolesScope { get; set; } = false;
    
    /// <summary>
    /// Set to true to update the user's settings.
    /// </summary>
    [JsonPropertyName("updateSettingsScope")]
    public bool UpdateSettingsScope { get; set; } = false;

    /// <summary>
    /// The new password of the user. To set a new password, the user must have the "updatePasswordScope" property set.
    /// </summary>
    [JsonPropertyName("newPassword")]
    public string? NewPassword { get; set; }
    
    /// <summary>
    /// The new theme of the user. To set a new theme, the user must have the "updateSettingsScope" property set.
    /// </summary>
    [JsonPropertyName("theme")]
    public string? Theme { get; set; }
    
    /// <summary>
    /// The new roles of the user. To set new roles, the user must have the "updateRolesScope" property set.
    /// </summary>
    [JsonPropertyName("roles")] 
    public IEnumerable<string> Roles { get; set; } = [];

    /// <summary>
    /// The nonce used to confirm the password change. The nonce is generated by the client (usually email application) and must be sent back to the server along with the new password.
    /// </summary>
    [JsonPropertyName("passwordConfirmationNonce")]
    public string? PasswordConfirmationNonce { get; set; }
    
}