using System.Collections.Specialized;
using System.Net;
using System.Text;
using System.Text.Json;
using Microsoft.Azure.Functions.Worker;
using Microsoft.Azure.Functions.Worker.Http;
using Moq;

namespace ProgramX.Azure.FunctionApp.Tests.HttpTriggers;

/// <summary>
/// Using the builder pattern, allows for the creation of a <see cref="TestHttpRequestData"/> instance.
/// </summary>
public class TestableHttpResponseDataBuilder
{
    private HttpStatusCode? _httpStatusCode=null;
    private NameValueCollection _query = new();
    private NameValueCollection _headers = new();
    private Uri _url = new("https://localhost");
    private IEnumerable<string> _roles = new List<string>();
    private bool? _useValidAuthorisation = null;
    private object? _payload = null;
    private string? _body = null;

    public TestableHttpResponseDataBuilder WithBody(string body)
    {
        _body = body;
        return this;
    }
    
    /// <summary>
    /// Specifies which HTTP Status Code the response created from the request should return.
    /// </summary>
    /// <param name="httpStatusCode">The <see cref="HttpStatusCode"/> to return.</param>
    /// <returns>A <see cref="TestableHttpRequestDataBuilder"/> which can be used to further
    /// configure the <see cref="TestHttpRequestData"/> that will be generated by
    /// <see cref="Build"/>.</returns>
    public TestableHttpResponseDataBuilder Returns(HttpStatusCode httpStatusCode)
    {
        _httpStatusCode = httpStatusCode;
        return this;
    }


    /// <summary>
    /// Build the <see cref="TestHttpRequestData"/> instance.
    /// </summary>
    /// <returns></returns>
    public HttpResponseData Build()
    {
//        var mockedHttpResponseData = new Mock<HttpResponseData>();
        
        var mockFunctionContext = new Mock<FunctionContext>();
        
        var testHttpRequestData = new TestHttpResponseData(
            mockFunctionContext.Object, 
            _httpStatusCode ?? HttpStatusCode.OK
            );
        
        if (_payload != null)
        {
            var serializedPayload = JsonSerializer.Serialize(_payload);
            testHttpRequestData.Body.Write(Encoding.UTF8.GetBytes(serializedPayload), 0, serializedPayload.Length);
        }

        if (_body != null)
        {
            testHttpRequestData.Body.Write(Encoding.UTF8.GetBytes(_body), 0, _body.Length);       
        }

        foreach (var header in _headers.AllKeys)
        {
            testHttpRequestData.Headers.Add(header,_headers[header]);
        }
        
        return testHttpRequestData;
    }
    
}